# Generated by Django 4.0.4 on 2022-04-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=20)),
                ('Date', models.DateField()),
                ('Description', models.TextField(max_length=1000)),
            ],
        ),
    ]
